apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: greeters.kindcontainer.dajudge.com
spec:
  group: kindcontainer.dajudge.com
  scope: Namespaced
  names:
    plural: greeters
    singular: greeter
    kind: Greeter
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: [ spec ]
          properties:
            spec:
              type: object
              required: [ greeting, host ]
              properties:
                greeting:
                  type: string
                host:
                  type: string